### ISSUE TITLE
Question: Is OpenAI Key Premium Plan a Requirement?

### ISSUE THREAD

**Issue by mbennette68** [AZHenley/Mirror#8]
Hi,

To use Mirror, does the OpenAI account need to be the non-free type or will the free key work?

I ask cause I got the error message, "**_Error: The model `gpt-4o` does not exist or you do not have access to it._**"

Thank you,
MB

**Comment by AZHenley** [comment]
I didn't realize there was a free tier! Looks like gpt3.5 turbo is included in the free tier, so you can use that instead. I have not done any testing on how well it performs for this task though.
